### ISSUE TITLE
How do I install deepspeed

### ISSUE THREAD

**Issue by JerryShiue** [kyegomez/RT-2#10]
When I was pip install rt2, an error occurred when running deepspeed, the error is as follows, I can't find a solution, help me

Collecting deepspeed (from palme->-r requirements.txt (line 6))
  Using cached deepspeed-0.10.2.tar.gz (858 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\shtseng\AppData\Local\Temp\pip-install-he0jlh01\deepspeed_3f29e5e48d7248c2937cac6abb05e625\setup.py", line 147, in <module>
          assert torch_available, "Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops."
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
       [WARNING]  unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by JerryShiue** [comment]
@kyegomez  Thanks, I also solved this problem

**Comment by metacav** [comment]
How did you solve this issue?

Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-5elv84x7/setup.py", line 31, in <module>
          import torch
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/torch/__init__.py", line 1239, in <module>
          from torch import onnx as onnx
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/torch/onnx/__init__.py", line 12, in <module>
          from . import (  # usort:skip. Keep the order instead of sorting lexicographically
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/torch/onnx/symbolic_caffe2.py", line 4, in <module>
          from torch.onnx import symbolic_helper, symbolic_opset9 as opset9
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/torch/onnx/symbolic_helper.py", line 611, in <module>
          def _onnx_unsupported(op_name: str, value: Optional[_C.Value] = None) -> NoReturn:
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/beartype/_decor/decorcache.py", line 77, in beartype
          return beartype_object(obj, conf)
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/beartype/_decor/decorcore.py", line 98, in beartype_object
          _beartype_object_fatal(obj, conf=conf, **kwargs)
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/beartype/_decor/decorcore.py", line 147, in _beartype_object_fatal
          beartype_nontype(obj, **kwargs)  # type: ignore[return-value]
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/beartype/_decor/_decormore.py", line 178, in beartype_nontype
          return beartype_func(obj, **kwargs)  # type: ignore[return-value]
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/beartype/_decor/_decormore.py", line 242, in beartype_func
          func_wrapper_code = generate_code(bear_call)
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/beartype/_decor/wrap/wrapmain.py", line 187, in generate_code
          code_check_return = _code_check_return(bear_call)
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/beartype/_decor/wrap/wrapmain.py", line 669, in _code_check_return
          reraise_exception_placeholder(
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/beartype/_util/error/utilerror.py", line 214, in reraise_exception_placeholder
          raise exception.with_traceback(exception.__traceback__)
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/beartype/_decor/wrap/wrapmain.py", line 618, in _code_check_return
          ) = make_func_wrapper_code(hint_sane, bear_call.conf, cls_stack)  # type: ignore[assignment]
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/beartype/_util/cache/utilcachecall.py", line 259, in _callable_cached
          raise exception
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/beartype/_util/cache/utilcachecall.py", line 251, in _callable_cached
          return_value = args_flat_to_return_value[args_flat] = func(
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/beartype/_decor/wrap/_wrapcode.py", line 86, in make_func_wrapper_code
          ) = make_check_expr(hint, conf, cls_stack)
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/beartype/_util/cache/utilcachecall.py", line 259, in _callable_cached
          raise exception
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/beartype/_util/cache/utilcachecall.py", line 251, in _callable_cached
          return_value = args_flat_to_return_value[args_flat] = func(
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/beartype/_check/code/codemake.py", line 706, in make_check_expr
          die_if_hint_pep_unsupported(
        File "/home/user/anaconda3/envs/rt2/lib/python3.9/site-packages/beartype/_util/hint/pep/utilpeptest.py", line 205, in die_if_hint_pep_unsupported
          raise BeartypeDecorHintPep484Exception(
      beartype.roar.BeartypeDecorHintPep484Exception: Function torch.onnx.symbolic_helper._onnx_unsupported() return PEP 484 type hint "typing.NoReturn" invalid in this type hint context (i.e., "typing.NoReturn" valid only as non-nested return annotation).
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
