### ISSUE TITLE
Callable' has no attribute '_abc_registry

### ISSUE THREAD

**Issue by sankexin** [kyegomez/RT-2#23]
pip install -r requirements.txt，这个项目pip安装库后pip没法用了怎么解决呢？
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.10/site-packages/pip/__init__.py", line 1, in <module>
    from typing import List, Optional
  File "/usr/local/lib/python3.10/site-packages/typing.py", line 1359, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/usr/local/lib/python3.10/site-packages/typing.py", line 1007, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'

**Comment by sankexin** [comment]
dataclasses lead to error? no corect dataclasses , how to solve ?
